### ISSUE TITLE
plot entropy vs. particular energy of realisation

### ISSUE THREAD

**Issue by kdomino** [iitis/polymer_entropy#22]
@soycapitan, for each realization there is the energy that corresponds to the chain formation just before docking (@NKruszewska you can explain).  Please plot entropy of particular realization as the function of such entropy. 6 plots for CS6 (3 ions x 2 angles) and 6 plots for HA

**Comment by soycapitan** [comment]
I need some clarification here.
We calculate entropy for pairs of angles in every realization. We have not defined so far the "realization entropy". We have calculated median entropy (and percentiles) from multiple pairs.

1. Do we want here to plot a set of 120+ plots (3 Ions x 2 angle pairs x 23 mers) ? A subset of these?
2. Do we want to assign `realization_entropy` equal to median/mean of subsequent entropies?
3. Or do we want to concatenate multiple columns and calculate on such data? Would it carry any physical sense?

**Comment by NKruszewska** [comment]
@soycapitan I need to think it over once again. We cant plot energy of binding on the x-axis because it not changes in many cases (for CS6 - I don't know how it is with HA). Realizations 1-3 are almost identical - they have the same energy, next 4-6, 7-9 also are the same. We can only order them by binding energies after MD - maybe, because the order will be different for different ions...
I will think about answers tomorrow.

**Comment by kdomino** [comment]
@soycapitan 

1. Mers are aggregated over in 2D hist. So we will have 3 ions x 2 angle pair for both polymers.

**Comment by kdomino** [comment]
Done (yet without binding energies in x axis) in #41

**Comment by soycapitan** [comment]
With energies in #42

**Comment by NKruszewska** [comment]
@soycapitan the plot looks very good.
