### ISSUE TITLE
Should we really use sign-changing algorithm?

### ISSUE THREAD

**Issue by NKruszewska** [iitis/polymer_entropy#23]
I'm trying to look on our histograms and on Ramachandran plot and I'm worried if it is good that we change the sign. If yes - which sign is correct... I really have no idea why we get in Yasara sometimes positive sometimes negative values but the program in previous simulations where we have used dihedral angles computation never did such problem. Looking on snapshots I see that it is possible that the angles change so much - the groups of atoms can rotate. Now in present results we still have sometimes positive and negative values (look on albumin+HA in fig 4) and I'm not sure if it is wrong. Maybe we shouldn't use any sign changing algorithms. Now we have sometimes situations that "red stain" on Phi(Psi) chart is up and next simulation we have it down. It can depend only if Yasara start from positive or start from negative values - it can be random (of course if we assume that Yasara do something wrong).
Summarizing: I think that we could spoiling the result by manipulating the sign.

**Comment by soycapitan** [comment]
I am going to provide a set of plots without angle sign changing.

**Comment by soycapitan** [comment]
Plots with original angles are on [gdrive](https://drive.google.com/drive/folders/1yZhA7yp_sP27zTfc_8XzoObf8O2GNmOD?usp=sharing) next to ones with _fixed_ angles.

A remark from my side: Please note that although angles of `-179` and `+179` look so distant on the plot in fact they are just 2 deg apart - we might want to change the reference point so that we do not plot absolute values but ones related to some point.
![Albumin+CS6_1_analysis_Ca_c8](https://user-images.githubusercontent.com/11042812/164721804-7f838a36-cd6c-4ac2-95e5-6210060da543.png)

In nature angles _wrap_ on the circle and we might need to think of a better way of visualising that fact.

**Comment by NKruszewska** [comment]
![image](https://user-images.githubusercontent.com/94965439/164724583-8204e8e7-5520-4979-b533-3dd59cc2daf4.png)

**Comment by soycapitan** [comment]
[pics_HA_original_angles](https://drive.google.com/drive/folders/1Pq3O0x7z_VrB_WGVzLe4R4cYr8AH715z?usp=sharing)
