### ISSUE TITLE
Analiogical plots for HA, reduce number of realisations.

### ISSUE THREAD

**Issue by kdomino** [iitis/polymer_entropy#28]
As I understand bind_energies (before simulations) are ordered from highest for realization 1 to lowest for realization 12 in the HA case.  To compare fairly CS6 and HA we should have also 10 realizations for HA. Shall we remove hence realization 11 and 12 in data2 (HA folder). 

Then ```bind_energies = { 
        ('Albumin+CS6','analysis'):
      ....
      ```  
in ```experiment.py``` can be extended on some way for `Albumin+HA`.

We took ``10`` realizations for CS6 but I guess these with the best ```bind_energies``` before simulations. We can filter in the same way HA, what is consistent with taking ```10``` best ```bind_energies``` , i.e. first ```10``` realizations.


@NKruszewska, what is your opinion?

**Comment by kdomino** [comment]
The ```bind_energies``` would have then ```10``` elements for each key.

**Comment by kdomino** [comment]
Btw. @soycapitan is it correct?

```bind_energies = { #FIXME this should be handled in a more flexible way
        ('Albumin+CS6','analysis'): {
          1: 4.353,
          2: 4.354,
          3: 4.348,
          4: 4.347,
          5: 4.339,
          6: 4.322,
          7: 4.314,
          8: 4.1875,
          9: 4.274,
          10: 4.249,
          11: 4.236,
          12: 4.186,
        }
    }
```

Why ```12``` realizations for 'Albumin+CS6'

**Comment by NKruszewska** [comment]
I suppose that it may be case of HA. For CS6 we have:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Natalia/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Natalia/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">
1 | 4.3560
-- | --
2 | 4.3560
3 | 4.3560
4 | 4.3540
5 | 4.3540
6 | 4.3540
7 | 4.3500
8 | 4.3500
9 | 4.3500
10 | 4.3480
</body>
</html>

So as you see - not good situation. It is caused by changing version of Yasara. In the new one the program didn't eliminate repetition of the result. I should notice it at the beggining and chose different realisations. But now we have no time. The realisations 1-3 are identical looking on map of contacts between HSA and CS6 but they are different when looking on their 3D structures. Thay also behave differently during MD simulations.

**Comment by NKruszewska** [comment]
@kdomino about CS6: it is a good situation if we wanted to compare very similar simulations: simulation with the same initial condition of the binding map but little various oriented in space. It is a great opportunity to test it. But it is a pity that we cant produce two charts: for CS6 and HA - to compare. Because in the case of CS6 we actually have only 4 different initial structures. Maybe we can describe it this way and while waiting for review we can do right simulations.

**Comment by kdomino** [comment]
We have to decide what to do, now

**Comment by kdomino** [comment]
So my suggestion:
- ```10``` realizations for both (remove ```11``` and ```12``` for ```HA```)
-  say that in case of SC6 we have only 4 different initial structures, unlikely ```HA```
-  plot entropy vs. n.o. of realization, say that it is not increasing in energy.

**Comment by NKruszewska** [comment]
I don't know what @Piotr8706 will propose. But my proposition is to do it right as you just wrote (in the figure caption, we can write binding energy values). Maybe let's make a bar graph to have labels on x axis not values 1-10?

**Comment by NKruszewska** [comment]
But I really want to see entropy values for all cases 1-3, 4-6 and 7-9 to compare them and see the differences.

**Comment by kdomino** [comment]
```10``` values of HA on one plot and ```10``` values of SC6 on the other plot

**Comment by kdomino** [comment]
with double ```x``` label, n.o. of realization and energy, ordered and spaced by n.o. realization

**Comment by NKruszewska** [comment]
Yes.

**Comment by kdomino** [comment]
I made a pull request that sort out some problems, i.e. we have now:

```
    bind_energies = { #FIXME this should be handled in a more flexible way
        ('Albumin+CS6','analysis'): {
          1: 4.3560,
          2: 4.3560,
          3: 4.3560,
          4: 4.3540,
          5: 4.3540,
          6: 4.3540,
          7: 4.3500,
          8: 4.3500,
          9: 4.3500,
          10: 4.3480,
        },
        ('Albumin+HA','analysis'): {
          1: 4.353,
          2: 4.354,
          3: 4.348,
          4: 4.347,
          5: 4.339,
          6: 4.322,
          7: 4.314,
          8: 4.1875,
          9: 4.274,
          10: 4.249,
        }
    }
```

and I remove two realizations for ```HA```.  @NKruszewska @Piotr8706, please check energies.

**Comment by NKruszewska** [comment]
@kdomino @soycapitan Sorry - I did a mistake! There are two energy lists in the log file and I didn't notice it. 4 hours ago I gave you the wrong one. Everything is ok with CS6. Energy list should be:

1 | 4.356
2 | 4.354
3 | 4.348
4 | 4.347
5 | 4.339
6 | 4.322
7 | 4.314
8 | 4.308
9 | 4.274
10 | 4.249

**Comment by NKruszewska** [comment]
@kdomino The same table for HA (i just got it from @Piotr8706 ):

1 | 5.416
2 | 4.984
3 | 4.945
4 | 4.715
5 | 4.69
6 | 4.688
7 | 4.687
8 | 4.684
9 | 4.635
10 | 4.62
11 | 4.583
12 | 4.575
